GET http://localhost:3000
###

POST http://localhost:3000
###

GET http://localhost:3000/12/
###

PUT http://localhost:3000/41/
###

DELETE http://localhost:3000/1/
###

GET http://localhost:3000
###

Get  http://localhost:3000/